### ISSUE TITLE
Convenience function for .obj in S3.get_object

### ISSUE THREAD

**Issue by randyzwitch** [JuliaCloud/AWS.jl#10]
Thanks for putting together this package Amit, it's been working pretty well on my S3 goofing around tonight.

As I played with the S3.get_object file to download a .csv file, I found myself needing to parse out the String object that is returned. Since I believe that downloading text data files will be a likely use of this package, it'd be great to be able to parse text files into arrays/DataFrames automatically.  

Here's the flow I did:

``` julia
resp = S3.get_object(env, "rzwitch/julia-test", "urls_10000.wsv");
#this splits on the newline character, which is enough in this toy case since I have a single column
url_array = split(resp.obj, "\n",-1,false) 
#Convert to DataFrame
testdf = DataFrame(url_array)

```

Alternatively, this could be suggested for the DataFrames package to deal with strings explicitly; I tried the `DataStream` function, but that didn't seem to work.

cc: @johnmyleswhite

**Comment by mattBrzezinski** [comment]
Closing this issue as it's been over 7 years, also not relevant since the release of 1.0.0.
