### ISSUE TITLE
How to use S3.put_object to upload a local file

### ISSUE THREAD

**Issue by akubisch** [JuliaCloud/AWS.jl#113]
Hi again,
sorry for a probably stupid question, but... Since I now have a working installation with my local endpoint, I would like to put a pdf file into it. How can I achieve this? If I use `S3.put_object(env, "mybucket", "test.pdf", "test.pdf")` all I get is a document trying to be a pdf but actually just being a small test file with the filename itself. As I get it, the first call to "test.pdf" sets the resulting filename and the second is the content. But how do I get the content from the pdf file in there? I also tried a `readstring("test.pdf")` and serialized it using `convert(Vector{Uint8}, readstring("test.pdf"))` (since this is what I get from a test file on the server), but that wasn't accepted by the function.

Sorry again, but despite fiddling around, I couldn't get it to work ;-)

**Comment by akubisch** [comment]
Further tried `f = open("test.pdf", "r")` and `S3.put_object(env, "mybucket", "test.pdf", f)` as well as `S3.put_object(env, "mybucket", "test.pdf", read(f))`, but none of them work, either - no method available...

**Comment by akubisch** [comment]
News! MD is working (and should have been, I just didn't have MbedTLS installed). Now, it has a problem with Request's put (f is an IOstream):
```
S3.put_object(env, "forecast-pdf", "Hallo", f)
```
results in
```
ERROR: MethodError: no method matching put(::URIParser.URI, ::IOStream; headers=Dict("Accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","Content-Type"=>"application/octet-stream","Authorization"=>"AWS XXXXXXXXXXXXXXXXXXXXXX=","x-amz-date"=>"Thu, 22 Feb 2018 15:03:22 GMT","User-Agent"=>"Requests.jl/0.0.0","Content-MD5"=>"Tc5fcR0zGgy4SLSCB1V61g=="))
Closest candidates are:
  put(::URIParser.URI; args...) at /home/alex/.julia/v0.6/Requests/src/Requests.jl:432
  put(::URIParser.URI, ::AbstractString; headers) at /home/alex/.julia/v0.6/Requests/src/Requests.jl:425
Stacktrace:
 [1] do_http(::AWS.AWSEnv, ::AWS.S3.RO) at /home/alex/.julia/v0.6/AWS/src/S3.jl:768
 [2] #do_request#33(::Bool, ::Function, ::AWS.AWSEnv, ::AWS.S3.RO) at /home/alex/.julia/v0.6/AWS/src/S3.jl:658
 [3] #put_object#30(::String, ::AWS.S3.PutObjectOptions, ::String, ::Function, ::AWS.AWSEnv, ::String, ::String, ::IOStream) at /home/alex/.julia/v0.6/AWS/src/S3.jl:556
 [4] put_object(::AWS.AWSEnv, ::String, ::String, ::IOStream) at /home/alex/.julia/v0.6/AWS/src/S3.jl:537
 [5] eval(::Module, ::Any) at ./boot.jl:235
 [6] eval(::Any) at ./boot.jl:234
 [7] macro expansion at /home/alex/.julia/v0.6/Atom/src/repl.jl:186 [inlined]
 [8] anonymous at ./<missing>:?
```

**Comment by tanmaykm** [comment]
Requests.jl seems to have changed the method signature some time back (after this https://github.com/JuliaWeb/Requests.jl/commit/488bc4ece65077f9e9bd43122b0881336e335e1b ?).

Dropping support for `IO` types for data may not have been intentional. Needs a deeper look, but likely fixable in Requests.jl.

**Comment by kcajf** [comment]
@mattBrzezinski what was the resolution here please? I'm still not able to make it work.

**Comment by mattBrzezinski** [comment]
> @mattBrzezinski what was the resolution here please? I'm still not able to make it work.

This project has been completely re-written from what was previously here. Could you issue with a small example and I can take a look?

**Comment by kcajf** [comment]
Ah, understood. What I'm trying to do is upload a local file to s3. I'd prefer to avoid having to load the full file into memory first, then upload it - it would be nice if it could be streamed directly from disk over HTTP. Is this possible?

**Comment by mattBrzezinski** [comment]
> Ah, understood. What I'm trying to do is upload a local file to s3. I'd prefer to avoid having to load the full file into memory first, then upload it - it would be nice if it could be streamed directly from disk over HTTP. Is this possible?

With this iteration of the package, unfortunately no this package is auto-generated in a strict format. I have not looked yet but [AWSS3.jl](https://github.com/JuliaCloud/AWSS3.jl) is a hand-made package and may contain what you're looking for.
