### ISSUE TITLE
Tagging new version/updating METADATA?

### ISSUE THREAD

**Issue by JohnHBrock** [JuliaCloud/AWS.jl#114]
There are some fixes in master I would love to have -- can someone with permissions tag a new version? I want to rely on version resolution instead of using `Pkg.checkout(...)`. Thanks!

**Comment by tanmaykm** [comment]
Tagged v0.4.1. Waiting for attobot to kick in.

**Comment by JohnHBrock** [comment]
I don't see the PR on the [METADATA.jl repo](https://github.com/JuliaLang/METADATA.jl/pulls). Did attobot ever kick in? I thought it was usually pretty fast.

**Comment by tanmaykm** [comment]
Yes. Don't know why it was stuck.
Worked now, after a delete and re-tag: https://github.com/JuliaLang/METADATA.jl/pull/13734
