### ISSUE TITLE
deprecate package?

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaCloud/AWS.jl#118]
It seems to me that this package is deprecated as everything has moved to AWSCore.jl and AWSSDK.jl.  Is there any future for this as a metapackage for the rest of the AWS stuff?  If not, should there be a deprecation notification?

**Comment by mattBrzezinski** [comment]
I am in the process of redesigning [AWSCore.jl](https://github.com/JuliaCloud/AWSCore.jl), and want to take this namespace over. See the re-design [here](https://github.com/mattBrzezinski/JuliaCloud-AWS-State), basically combining `AWSCore.jl` and `AWSSDK.jl` together.

I'd like to rename this package, and archive it to free up the namespace. Not sure what it should be renamed to, @omus suggested `AWS2013.jl`, after when it was created. Or `AWS2018.jl` when it stopped being updated.

Any thoughts on this?
@tanmaykm 
@iamed2 
@jingpengw

**Comment by jingpengw** [comment]
either one sounds good to me.

**Comment by tanmaykm** [comment]
The re-design looks cool! And either name sounds good to me for renaming.

AWS.jl is not there in the General registry, so renaming would be okay there.

But it was present in the older METADATA.jl. I did not find any guidelines regarding renaming packages in METADATA.jl. I wonder if we should be concerned about that, and do we need to do someting to adress that?

**Comment by mattBrzezinski** [comment]
I don't think that [Metadata.jl](https://github.com/JuliaLang/METADATA.jl/commits/metadata-v2) is being used anymore, apart from the removal of a file last week the last tagged package was back on 2019-10-13.

**Comment by aviks** [comment]
Existing 0.5 and 0.6 users (yes, there are still a few of those!) still use METADATA, even if new packages are not being developed. `Pkg` in 0.6 does a git checkout when adding a package. If new code lives at this URL, that will break all those users. So just renaming this package is not a good idea. 

It may be possible to change the url in  METADATA, but it's still a bit risky.

**Comment by omus** [comment]
Probably the most seamless way to transition would be just to make the changes as part of this repo and leave the history of this intact. That way we wouldn't have to make any changes to METADATA.jl

**Comment by aviks** [comment]
Yup, that's a good plan
