### ISSUE TITLE
Setting page redirects on S3

### ISSUE THREAD

**Issue by staticfloat** [JuliaCloud/AWS.jl#12]
I'd like to be able to set page redirects in S3 using your APIs.

Here's the documentation: http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

It really just boils down to sending a particular `x-amz-` header in the request, I believe the header is `x-amz-website-redirect-location`.

**Comment by mattBrzezinski** [comment]
Closing this issue as it's been almost 7 years, also not relevant since the release of 1.0.0.
