### ISSUE TITLE
Acceptance test: can AWSServices.s3 replace AWSS3.s3?

### ISSUE THREAD

**Issue by iamed2** [JuliaCloud/AWS.jl#143]
I think this would be a good test to see that we've covered our bases. A lot of the other functions have convenience functionality added so I don't think they can directly be replaced by `@service S3`, but the base `s3` should be doable. It would be nice to replace all uses of `do_request` in the wild.

**Comment by mattBrzezinski** [comment]
This is something that I've been thinking about recently, and how to do some real world testing. I think testing this out in both in the AWSS3 and AWSSQS packages would be really helpful!
