### ISSUE TITLE
Issues with docstrings for high-level services

### ISSUE THREAD

**Issue by omus** [JuliaCloud/AWS.jl#168]
- [ ] Docstring function name doesn't match actual function name ([`CreateConnectorProfile` vs. `create_connector_profile`](https://github.com/JuliaCloud/AWS.jl/blob/master/src/services/appflow.jl#L8))
- [ ] Docstrings aren't actually [attached to any function/method](https://github.com/JuliaCloud/AWS.jl/blob/master/src/services/appflow.jl#L21). I'd suggest attaching it to the function in general (e.g. `function create_connector_profile end`)
- [ ] Docstring function name cannot be [called without arguments](https://github.com/JuliaCloud/AWS.jl/blob/master/src/services/appflow.jl#L8). Just remove the `()`
- [ ] Parameters should probably also be in [snake_case instead of CamelCase](https://github.com/JuliaCloud/AWS.jl/blob/master/src/services/appflow.jl#L14)?

**Comment by mattBrzezinski** [comment]
I'll tack this in as well, but a line character limit would be nice to impose here. Currently if parameter docstr is say 500 character, they'll all sit on the same line. We should limit this to 140, break on the next word and continue the remainder of the docstring on the next line.

**Comment by mattBrzezinski** [comment]
And since we're touching on docstrs, add [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl) to the package too.

**Comment by mattBrzezinski** [comment]
Handle lists as well.

https://github.com/JuliaCloud/AWS.jl/pull/171#discussion_r482984692
