### ISSUE TITLE
Package Compat not found 

### ISSUE THREAD

**Issue by tclements** [JuliaCloud/AWS.jl#169]
Trying out the recent release of AWS: 

```julia
(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [fbe9abb3] AWS v1.1.0
```

Trying out the example from the README: 

```julia 
julia> using AWS

julia> @service S3
ERROR: LoadError: ArgumentError: Package Compat not found in current path:
- Run `import Pkg; Pkg.add("Compat")` to install the Compat package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:893
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include(::Module, ::String) at ./Base.jl:368
 [4] top-level scope at /home/timclements/.julia/packages/AWS/W7Jsa/src/AWS.jl:99
 [5] top-level scope at REPL[3]:1
in expression starting at /home/timclements/.julia/packages/AWS/W7Jsa/src/services/s3.jl:5
```

Seems Compat is not installing

**Comment by mattBrzezinski** [comment]
Interesting, I can replicate this on my machine. I'll look into this, thanks for bringing it up.

**Comment by mattBrzezinski** [comment]
Looks like to fix this we need to change:

> https://github.com/JuliaCloud/AWS.jl/blob/f55efaa72ade5c05dcdf955d05df9c9364a97a75/src/services/s3.jl#L5

with:

```julia
using AWS: Compat
```

I'm not quite understanding why it's not available. Digging a bit further into this, to see if I can come up with a better answer. If not I'll make the required changes and publish a new version.

**Comment by omus** [comment]
> I'm not quite understanding why it's not available

The reason Compat.jl is not being found is because `@service S3` is being expanded in the context of the REPL here which does not have Compat.jl as part of the listed packages available for import. The solution here is to use `using AWS: Compat` which just requires that AWS.jl declares Compat.jl as a dependency.

**Comment by omus** [comment]
There used to be an option where you could instead have the code be written back into AWS.jl depending on the services being used by other packages but I think that is now no longer an option as you'll see warnings about incremental compilation being broken.

**Comment by mattBrzezinski** [comment]
Yeah that's the conclusion I came across, I was curious if modifying the `Expr` in `macro service` would enable loading it in, but I wasn't able to find any documentation on how what you could replace `:toplevel` with. Just playing in the REPL with what is and isn't available resulted in no findings either.

I think #170 is a good fix in that case.

**Comment by mattBrzezinski** [comment]
`v1.1.1` is released, just tested and confirmed it's working.
