### ISSUE TITLE
Type piracy of Base.merge

### ISSUE THREAD

**Issue by oxinabox** [JuliaCloud/AWS.jl#205]
I'm not sure this is even used.
https://github.com/JuliaCloud/AWS.jl/blob/master/src/utilities.jl#L5

**Comment by mattBrzezinski** [comment]
This is used for defining high-level definitions when we have some default parameters to pass along, or some required parameters and optional ones I believe.

**Comment by oxinabox** [comment]
Can you cange it from

```julia
Base.merge(_merge, a::AbstractString, b::AbstractString) = _merge(a, b)
```
to
```
Base.merge(::typeof(_merge), a::AbstractString, b::AbstractString) = _merge(a, b)
```

AFAICT `Base.merge` is never used directly, only via `mergewith(_merge...`
and `mergewith` just passes its first argument to `merge` which i guessi s where this is hit
so that would still get hit by `mergewith`
