### ISSUE TITLE
new install julia ICU.jl error

### ISSUE THREAD

**Issue by merl-dev** [JuliaCloud/AWS.jl#23]
This is new:
julia> using AWS
ERROR: invalid base 10 digit 'L' in "LL"
 in error at error.jl:21
 in parseint_nocheck at string.jl:1520
 in parseint_nocheck at string.jl:1548
 in int at string.jl:1559
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading C:\Users\user.julia\v0.3\ICU\src\ICU.jl, in expression starting on line 59
while loading C:\Users\user.julia\v0.3\Calendar\src\Calendar.jl, in expression starting on line 1
while loading C:\Users\user.julia\v0.3\AWS\src\AWS.jl, in expression starting on line 3

**Comment by tanmaykm** [comment]
closing as outdated, probably wasn't an AWS.jl issue
