### ISSUE TITLE
create_bucket in region outside us-east-1

### ISSUE THREAD

**Issue by tclements** [JuliaCloud/AWS.jl#243]
I'm on the latest release of AWS: 

```julia
(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [fbe9abb3] AWS v1.19.0
``` 
I'm having trouble creating buckets outside of the default `us-east-1` region: 

```julia
using AWS
AWS.@service S3
aws_config = AWS.AWSConfig(region="us-west-2")
S3.create_bucket("asdjkhaskdjfhakjsdhf",aws_config=aws_config) # random bucket name 

ERROR: AWS.AWSExceptions.AWSException("IllegalLocationConstraintException", "The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.", EzXML.Document(EzXML.Node(<DOCUMENT_NODE@0x0000000001c2c170>)), HTTP.ExceptionRequest.StatusError(400, "PUT", "/asdjkhaskdjfhakjsdhf", HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
x-amz-request-id: F562D415A7A48B9D
x-amz-id-2: lL3rjF0IYLsMydEWbrN2Ymld+tt33m70aurrFocPX8ancWgfPRYfBproGJMaote3fYwDcDxXqu8=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 09 Nov 2020 21:36:18 GMT
Server: AmazonS3
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message><RequestId>F562D415A7A48B9D</RequestId><HostId>lL3rjF0IYLsMydEWbrN2Ymld+tt33m70aurrFocPX8ancWgfPRYfBproGJMaote3fYwDcDxXqu8=</HostId></Error>"""))
```
It looks like I need to set the LocationConstraint to `us-west-2`. This is done in AWSS3.jl with the [s3_create_bucket ](https://github.com/JuliaCloud/AWSS3.jl/blob/ad21678cbb5fa2dda8192bfd28a5a7de3a757d83/src/AWSS3.jl#L303-#L310) function but haven't figured out the correct syntax yet to work with AWS.jl. 

I can confirm that 

```julia 
S3.create_bucket("asdjkhaskdjfhakjsdhf")
```

works as expected in creating a new bucket in `us-east-1`

**Comment by mattBrzezinski** [comment]
This is a bit of a PITA to make bucket in a different region. To create a bucket in a different region you need to pass in a `CreateBucketConfiguration` optional argument.

Here's an example to make a bucket in `us-east-2`:
```julia
using AWS
@service S3

aws = AWSConfig(region="us-east-2")
bucket_name = "mattbr-us-east-2"

content = """
         <CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
           <LocationConstraint>$(aws.region)</LocationConstraint>
         </CreateBucketConfiguration>"""

args = Dict("body"=>content)
S3.create_bucket(bucket_name, args)
S3.head_bucket(bucket_name)
```

**Comment by tclements** [comment]
Thanks! I had the `content` value correct but tried `CreateBucketConfiguration` as the key rather than `body`.

**Comment by mattBrzezinski** [comment]
> Thanks! I had the `content` value correct but tried `CreateBucketConfiguration` as the key rather than `body`.

Yeah, this is something which I need to document. It's a bit counter-intuitive, I'll play around in the future with this but it might be possible to combine everything into a `body` argument and pass it along. The `CreateBucketConfiguration` actually doesn't specify a [location](https://github.com/aws/aws-sdk-js/blob/master/apis/s3-2006-03-01.normal.json#L2543) in the JS API, so I think that means it defaults to the `body` of the request.

**Comment by QuantumBits** [comment]
One thing I want to point out that got me hung up for a while is that when you call `S3.create_bucket(bucket_name, args)`, it would appear that the dictionary `args` is emptied after every call to `S3.create_bucket`. 

```julia

julia> ags
Dict{String, String}()

julia> args = Dict("body"=>content)
Dict{String, String} with 1 entry:
  "body" => "<CreateBucketConfiguration xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">\n           <LocationConstraint>us-west-1</LocationConstraint>\n                    </CreateBucketConfiguration>"

julia> S3.create_bucket(bucket_name, args)
UInt8[]

julia> args
Dict{String, String}()
```

So, you either need to repopulate `args` before each call, or create the `args` dictionary directly in place like so:

```julia
S3.creat_bucket(bucket_name, Dict("body"=>content))
```

**Comment by mattBrzezinski** [comment]
> One thing I want to point out that got me hung up for a while is that when you call `S3.create_bucket(bucket_name, args)`, it would appear that the dictionary `args` is emptied after every call to `S3.create_bucket`.
> 
> ```julia
> julia> ags
> Dict{String, String}()
> 
> julia> args = Dict("body"=>content)
> Dict{String, String} with 1 entry:
>   "body" => "<CreateBucketConfiguration xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">\n           <LocationConstraint>us-west-1</LocationConstraint>\n                    </CreateBucketConfiguration>"
> 
> julia> S3.create_bucket(bucket_name, args)
> UInt8[]
> 
> julia> args
> Dict{String, String}()
> ```
> 
> So, you either need to repopulate `args` before each call, or create the `args` dictionary directly in place like so:
> 
> ```julia
> S3.create_bucket(bucket_name, Dict("body"=>content))
> ```

I'm not well versed in why this happens, it's something to do with [HTTP.jl](https://github.com/JuliaWeb/HTTP.jl) I believe.

**Comment by QuantumBits** [comment]
So I think I found the offending line: https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWS.jl#L210

Looks like the `body` field in particular is being `pop!`ed out for some reason?

**Comment by mattBrzezinski** [comment]
> So I think I found the offending line: https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWS.jl#L210
> 
> Looks like the `body` field in particular is being `pop!`ed out for some reason?
> 
> Oh and for reference that `_pop!` function is defined here: https://github.com/JuliaCloud/AWS.jl/blob/master/src/utilities/utilities.jl#L76

They're popped off because we do not want to include them in the `resource` or `query_str` here,

- https://github.com/JuliaCloud/AWS.jl/blob/fb43edd6d09b3c4a71050c0140d164987d970add/src/AWS.jl#L216-L217

**Comment by QuantumBits** [comment]
Gotcha - okay then I guess for those of us working in non-us-east-1 regions we'll just have to deal with this until a work-around is made. I think I might file an issue to at least keep track of this.
