### ISSUE TITLE
Line length in autogenerated files

### ISSUE THREAD

**Issue by fredrikekre** [JuliaCloud/AWS.jl#279]
This issue is pretty drive-by, but I happened to look at the source for something and noticed that lines are incredibly long, in particular for some doc strings. Just as an example, looking at https://github.com/JuliaCloud/AWS.jl/blob/master/src/services/s3.jl in the github web view is pretty difficult. Would it be possible to limit line lengths?
One option would be to run JuliaFormatter on the files.

---

Edit, maybe I should have posted like this:
```
This issue is pretty drive-by, but I happened to look at the source for something and noticed that lines are incredibly long, in particular for some doc strings. Just as an example, looking at https://github.com/JuliaCloud/AWS.jl/blob/master/src/services/s3.jl in the github web view is pretty difficult. Would it be possible to limit line lengths? One option would be to run JuliaFormatter on the files.
```
:)

**Comment by nickrobinson251** [comment]
> One option would be to run JuliaFormatter on the files.

Unfortunately I don't think JuliaFormatter limits line lengths on docstrings. At least, it didn't when i tried running `format_file` on the `src/service/` files, using JuliaFormatter v0.13.

I do think running JuliaFormatter on the generated files is still a good idea, as it'll make the _code_ more readable. But it's not such a quick-fix for the docstrings. 

Also, while i agree it'd be good to impose line limits on the docstrings in the src code, hopefully reading the docs will be made much easier by having hosted the docs which will autoamatically wrap the lines at a sensible limit (cf #267 /#289)
