### ISSUE TITLE
RestXMLService do not pass a request body where required

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaCloud/AWS.jl#280]
It seems that some services which require a request body instead put the body options elsewhere.

The example in which I discovered this was [SelectObjectContent](https://docs.aws.amazon.com/AmazonS3/latest/API/API_SelectObjectContent.html) for S3.  The `select_object_content` indeed takes the arguments that are required in the request body, however, to get into the body they should be placed in an inner dict called `"body"`, but instead they make it all the way to `_generate_rest_resource` which sticks them in the URL.

Instead, the method should look something like this
```
function select_object_content(Bucket, Expression, ExpressionType, InputSerialization, Key, OutputSerialization;
                               aws_config::AbstractAWSConfig=global_aws_config())
    s3("POST", "/$(Bucket)/$(Key)?select&select-type=2",
        Dict{String, Any}("body"=>Dict("Expression"=>Expression, "ExpressionType"=>ExpressionType,
                                       "InputSerialization"=>InputSerialization, "OutputSerialization"=>OutputSerialization));
        aws_config=aws_config)
end
```
Though, this does not address the issue of formatting the body as XML, which much to my frustrating, does not seem like something that can be done easily with XMLDict, at least not with a proper format.

It seems that the bigger problem here is that the API generator for XML's is not properly figuring out what should go in the body.

**Comment by mattBrzezinski** [comment]
I'm currently afk, but this probably is #219 
I'll read through this fully on Monday.

**Comment by ExpandingMan** [comment]
Yup, looks like the same issue, thanks.

**Comment by mattBrzezinski** [comment]
Closing in favour of #219
