### ISSUE TITLE
Some characters are not properly URI escaped in S3 URIs

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaCloud/AWS.jl#297]
I discovered that some S3 paths which are fine using the AWS CLI result in
errors using AWSS3.jl, and I think this is the right place to report because
this is where the escaping happens.

Specifically, I found that any path with a `+` in it would cause an
`AWS.AWSExceptions.AWSException` with `"SignatureDoesNotMatch", "The request
signature we calculated does not match the signature you provided. Check your
key and signing method."`.  Manually escaping the `+` would cause the request to
return the contents of the object with `+` in its key.

The custom URI escaping rules used here don't seem to reflect the most recent
AWS guidelines about what characters are okay, which "might require special
handling", and which are actively to be avoided (see
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html).

`+` is on the list of characters that "might require special handling", but it
also seems to be automatically escaped somewhere in AWS's pipeline leading to
the signature mismatch.  I've also confirmed informally that a key containing
all of those characters surrounds a roundtrip when they're URI encoded and show
up in the correct unencoded form with `aws s3 ls ...`.

I think the fix is pretty simple but wanted to report the issue here first; I'll
open a PR soon.

**Comment by mattBrzezinski** [comment]
Closed in #299
