### ISSUE TITLE
Pls put how to setup credentials and region in the README, so I can get on with my life.

### ISSUE THREAD

**Issue by ramboldio** [JuliaCloud/AWS.jl#318]

**Comment by mattBrzezinski** [comment]
If you follow the AWS CLI configuration [basics](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html) you should be good to go. This package looks in a similar order to Boto3 for [credentials](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html). I'll keep this open to add a page to the documentation to explain this in more depth.

**Comment by ramboldio** [comment]
ok cool thanks
