### ISSUE TITLE
Error compiling hmacsha1_digest on Windows 7

### ISSUE THREAD

**Issue by AndrewBMartin** [JuliaCloud/AWS.jl#33]
Stack trace reads:

ERROR: error compiling hmacsha1_digest: could not load module libcrypto: %1 is n
ot a valid Win32 application.

 in canonicalize_and_sign at C:\Users\Andrew Martin.julia\v0.3\AWS\src\S3.jl:69
7
 in do_http at C:\Users\Andrew Martin.julia\v0.3\AWS\src\S3.jl:614
 in do_request at C:\Users\Andrew Martin.julia\v0.3\AWS\src\S3.jl:564
 in get_object at C:\Users\Andrew Martin.julia\v0.3\AWS\src\S3.jl:392

Running on 64-bit Windows 7.

**Comment by s2maki** [comment]
libcrypto doesn't exist (AFAIK) for Windows.  You need to substitute libeay32.dll.  See pull request #32, let me know if that helps.

**Comment by AndrewBMartin** [comment]
Thanks, @s2maki. Adding the DLL led to an error with HTTPClient.

**Comment by tanmaykm** [comment]
seems to have been fixed by #43
