### ISSUE TITLE
S3.complete_multipart_upload documentation fix "CompleteMultipartUpload" to "body"

### ISSUE THREAD

**Issue by anj00** [JuliaCloud/AWS.jl#376]
[complete_multipart_upload](https://juliacloud.github.io/AWS.jl/stable/services/s3.html#Main.S3.complete_multipart_upload-Tuple{Any,%20Any,%20Any}) documentation says that one should put data under "CompleteMultipartUpload", but aws docs says it should be part of the "body"

Maybe documentation should say that one should generate xml as well

**Comment by mattBrzezinski** [comment]
These docstrs are auto-generated with what AWS themselves provide, [here](https://github.com/aws/aws-sdk-js/blob/508ee7cd2b207c2c42f04c6c70bc5075242cdc37/apis/s3-2006-03-01.normal.json#L50).

The documentation for the [MultipartUpload](https://github.com/aws/aws-sdk-js/blob/508ee7cd2b207c2c42f04c6c70bc5075242cdc37/apis/s3-2006-03-01.normal.json#L2055-L2061) also do not specify that it needs to be part of the body, so it's up to the end-user to determine where to place it really through trial-and-error or having the knowledge. There's not much more to do here for auto-generated code.

[AWSS3.jl](https://github.com/JuliaCloud/AWSS3.jl/blob/2b564443281d72c5520cbc3a156e479c35d9ee2a/src/AWSS3.jl#L604-L668) hides these details itself by placing things properly.
