### ISSUE TITLE
Typo in ec2_simple.jl: Passing in the right environment

### ISSUE THREAD

**Issue by pcmoritz** [JuliaCloud/AWS.jl#38]
Dear all,

thanks for this package!

Line 203 of ec2_simple.jl (commit de12551) should be replaced with

```
hosts = ec2_hostnames(instances, env=env)
```

(the env=env part was missing). Without this change, AWS.EC2 can't find the instance if it is not in the region us-east-1.

All the best,
Philipp.

**Comment by tanmaykm** [comment]
seems to have been fixed in one of the later commits: https://github.com/JuliaCloud/AWS.jl/blob/5aba846a24145c027a2139b51fd212a41b9c76ac/src/ec2_simple.jl#L203
