### ISSUE TITLE
S3 URIs not getting escaped?

### ISSUE THREAD

**Issue by jsahil730** [JuliaCloud/AWS.jl#387]
Hi,
Recently I encountered an S3 bug where it doesn't escape certain characters in the Key which leads to AWS reporting the following error -
> Encountered exception : AWSException: SignatureDoesNotMatch -- The request signature we calculated does not match the signature you provided. Check your key and signing method.  
  
The Key contained `:` (eg `18T18:16:54.json`) which I had to manually escape before asking for the file to be downloaded; I'm worried if this was forgotten or is it intended to be this way?

**Comment by mattBrzezinski** [comment]
Just need to add in `:` to the [_clean_s3_uri function](https://github.com/JuliaCloud/AWS.jl/blob/c55532192b2bfcdc2e0a31ebe39e9700070f8c38/src/utilities/utilities.jl#L42). At this point we may as well include all characters from the [special handling](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) section as they should work.

Example PR for this can be found here https://github.com/JuliaCloud/AWS.jl/pull/386
