### ISSUE TITLE
[Downloads backend] are we `close`ing streams correctly?

### ISSUE THREAD

**Issue by ericphanson** [JuliaCloud/AWS.jl#433]
Ref https://github.com/JuliaCloud/AWS.jl/pull/396#discussion_r694661438

**Comment by c42f** [comment]
> I think maybe one thing to do is to just replace all usage of `BufferStream` with `IOBuffer`. I dunno if there is a specific reason that we are currently using `BufferStream`

I think I may have found the reason for this.  It turns out that `HTTP.StreamLayer` actually closes the stream:

https://github.com/JuliaWeb/HTTP.jl/blob/cfcc595449b9de8869b28f04dcb25ad1f14438e3/src/StreamRequest.jl#L149

But a closed `IOBuffer` may not have its buffer read:

```julia
julia> io = IOBuffer()
       close(io)
       read(io)
ERROR: ArgumentError: read failed, IOBuffer is not readable
...
```

The underlying problem here may be that `Base` had no distinction between `closeread()` and `closewrite()`.

* HTTP.jl calls `close` and assumes it means `closewrite` (I guess). But this makes it unusable with `IOBuffer`
* Downloads.jl doesn't close the stream at all which means the caller needs to close it if it's a `BufferStream`.

See also https://github.com/JuliaLang/julia/issues/24526

**Comment by c42f** [comment]
Another cross ref: It's a known bug that `IOBuffer` doesn't work with HTTP.jl :cry:  https://github.com/JuliaWeb/HTTP.jl/issues/543

**Comment by vtjnash** [comment]
`IOBuffer()` is a file-like object, so it is incompatible with streaming modification. Use `BufferStream` for a stream-like object.

**Comment by omus** [comment]
> `IOBuffer()` is a file-like object, so it is incompatible with streaming modification. Use `BufferStream` for a stream-like object.

@vtjnash can you elaborate more? Unfortunately `Base.BufferStream` is undocumented and unexported and it would be great to know more about when it should be used and why.

**Comment by vtjnash** [comment]
Using IOBuffer leaves you vulnerable to truncation and data loss. `Base.BufferStream` needs to be exported, since it does not have that vulnerability, but is otherwise pretty much a drop-in replacement.

**Comment by vtjnash** [comment]
The exception is if you know that the data is being written synchronously (as HTTP does), as then you can treat the output as a file, instead of expecting a stream.

**Comment by omus** [comment]
I'll mention I find `Base.BufferStream` rather quirky as it needs to be closed to use `read(::IO)` (as opposed to `IOBuffer` which can only be read while open) and it [isn't seekable](https://github.com/JuliaLang/julia/issues/24465)

**Comment by omus** [comment]
The reason I was asking about `Base.BufferStream` was because #384 moves away from using it in favour of internally using `IOBuffer`.

**Comment by vtjnash** [comment]
Yes, because you can read immediately, it is vulnerable to losing your data (if it is concurrently used with `.writable = true`). Generally, HTTP avoids this though, by blocking the main `.get` call until IOBuffer is fully written.

**Comment by omus** [comment]
As of AWS.jl 1.63.0 (#384) both the `DownloadBackend` and `HTTPBackend` no longer close the streams when using the feature `use_response_type` (e.g. `@service S3 use_response_type=true`). By default the response type uses an `IOBuffer` but any user supplied `IO` can be provided via `"response_stream"` (note: I/O types that are seekable work best).

When not enabling the `use_response_type` feature the current behaviour as of AWS 1.62.1 remains unchanged.

**Comment by iamed2** [comment]
> any user supplied IO can be provided via `"response_stream"` (note: I/O types that are seekable work best).

non-seekable I/O types specifically do not work when encountering errors: https://github.com/JuliaCloud/AWSS3.jl/issues/249
