### ISSUE TITLE
Should `_http_request` only close streams it has created?

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaCloud/AWS.jl#468]
Follow up to https://github.com/JuliaCloud/AWS.jl/pull/467#issuecomment-929416121 (see also https://github.com/JuliaCloud/AWS.jl/issues/433)

Roughly, HTTP.jl v0.9.15 changed to not `close` streams within `HTTP.request` (see https://github.com/JuliaWeb/HTTP.jl/pull/752, https://github.com/JuliaWeb/HTTP.jl/issues/543, https://github.com/JuliaWeb/HTTP.jl/issues/772).

Here in AWS.jl, we were relying on the previous HTTP behaviour of calling `close` on the `response_stream`, so https://github.com/JuliaCloud/AWS.jl/pull/467 reintroduces the `close` in our internal `AWS._http_request` helper. 

But this was done as simplest way to get back to the previous HTTP behaviour. We might instead want to re-evaluate indiscriminately calling `close` on the stream, which a user could have provided

**Comment by omus** [comment]
Copied my response from https://github.com/JuliaWeb/HTTP.jl/issues/772#issuecomment-929621744 as it is relevant here:

> It should be pointed out that using `response_stream` for HTTP.jl 0.9.14 and below only really worked (I believe) with the unexported `Base.BufferStream`. The implementation of this stream seems to require the it be be closed in order for it to be read from. Most streams don't work this way.
> 
> I think the general rule should be that you shouldn't close `IO` instances that you didn't create.

**Comment by nickrobinson251** [comment]
Care to make a PR? I think it's roughly Fredrik's suggested diff (https://github.com/JuliaCloud/AWS.jl/pull/467#discussion_r717666189) plus a test that user-given IO-streams do not get closed?

**Comment by omus** [comment]
> Care to make a PR? I think it's roughly Fredrik's suggested diff ([#467 (comment)](https://github.com/JuliaCloud/AWS.jl/pull/467#discussion_r717666189)) plus a test that user-given IO-streams do not get closed?

Sure. I'll be rolling it into #384 as I need to update it to not break the current behaviour and then this change can be opt-in

**Comment by omus** [comment]
As of AWS.jl 1.63.0 (#384) streams are no longer closed when using the feature `use_response_type` (e.g. `@service S3 use_response_type=true`). If you enable this feature and pass in a `Base.BufferStream` you're responsible for closing it yourself.
 
When not enabling the `use_response_type` feature the current behaviour as of AWS 1.62.1 remains unchanged.
