### ISSUE TITLE
DownloadsBackend inconsistently closes streams

### ISSUE THREAD

**Issue by omus** [JuliaCloud/AWS.jl#471]
The following test case is from #470:
```julia
@testset "issue 466" begin
    file_name = "hang.txt"

    try
        S3.put_object("anewbucket", file_name)

        # Note: Using `eof` for these tests can hang when using an unclosed `Base.BufferStream`

        stream = S3.get_object("anewbucket", file_name, Dict("return_stream" => true))
        if AWS.DEFAULT_BACKEND[] isa AWS.HTTPBackend
            @test !isopen(stream)
        else
            @test isopen(stream)
        end

        stream = Base.BufferStream()
        S3.get_object("anewbucket", file_name, Dict("response_stream" => stream))
        if AWS.DEFAULT_BACKEND[] isa AWS.HTTPBackend
            @test !isopen(stream)
        else
            @test_broken isopen(stream)
        end

        stream = Base.BufferStream()
        S3.get_object(
            "anewbucket",
            file_name,
            Dict("response_stream" => stream, "return_stream" => true),
        )
        if AWS.DEFAULT_BACKEND[] isa AWS.HTTPBackend
            @test !isopen(stream)
        else
            @test isopen(stream)
        end
    finally
        S3.delete_object("anewbucket", file_name)
    end
end
```
Note how when using a non-`IOBuffer` and not using the `"return_stream"` parameter that the I/O stream is closed but in all other cases it leaves the stream open. This inconsistency should not be present.

Additionally, most likely the behaviour of the HTTPBackend and the DownloadsBackend should made to be consistent.

**Comment by omus** [comment]
Related to #433

**Comment by ericphanson** [comment]
Just to add another ref, I think this is case 2 from https://github.com/JuliaCloud/AWS.jl/pull/396#discussion_r695678666

**Comment by omus** [comment]
As of AWS.jl 1.63.0 (#384) streams are no longer closed when using the feature `use_response_type` (e.g. `@service S3 use_response_type=true`). If you enable this feature and pass in a `Base.BufferStream` you're responsible for closing it yourself.

When not enabling the `use_response_type` feature the current behaviour as of AWS 1.62.1 remains unchanged.
