### ISSUE TITLE
Add various libraries to the AMI

### ISSUE THREAD

**Issue by ViralBShah** [JuliaCloud/AWS.jl#5]
I guess this is the first Julia AMI for general purpose usage. Perhaps we should make sure that this has all the various debian dependencies pre-installed so that maximal number of packages can work out of the box. It would be nice to also include HDFS in here.

Should a script for creating a Julia-AMI out of a stock Ubuntu install be included in the julia contrib?

Cc: @loladiro @pao @staticfloat

**Comment by tanmaykm** [comment]
closing as outdated
