### ISSUE TITLE
S3.get_object sometimes returning incomplete ranged data without error

### ISSUE THREAD

**Issue by IanButterworth** [JuliaCloud/AWS.jl#515]
On modest/slow internet connections we're seeing `S3.get_object` sometimes return incomplete range chunks without error or warning
The MWE below is on a public 14.4 GB object so it should be testable.

Our work-around for this is to check the length returned and retry if incorrect, which seems to work.

But this seems like something that could/should be caught by the HTTP backend error handling?
Further, the length check is only checking length, not content. Looking into whether ranged S3 GETs can be checksum-ed, it appears that the `ETag` of these kind of requests is only in special cases the MD5 of the chunk, namely when the file was uploaded in the same chunks, which is a little limiting. But my understanding may be wrong here.

Is there perhaps a HTTP exception not being caught?

julia 1.6.3
```julia
julia> import Pkg; Pkg.activate(temp=true); Pkg.add("AWS")
  Activating new environment at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_4sjiZA/Project.toml`
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_4sjiZA/Project.toml`
  [fbe9abb3] + AWS v1.71.0
...

julia> using AWS: AWS, @service

julia> @service S3
Main.S3

julia> aws_config = AWS.AWSConfig(region = "us-east-1")
AWS.AWSConfig((xxx, yyy, 146138512-12-31T23:59:59), "us-east-1", "json")

julia> data = S3.get_object("ryft-public-sample-data", "demo_searchlynx_example.tgz", Dict("headers" => Dict("Range"=>"bytes=0-16777215")); aws_config);

julia> typeof(data)
Vector{UInt8} (alias for Array{UInt8, 1})

julia> Base.format_bytes(length(data))
"16.000 MiB"

julia> @sync for i in 1:10
           @async begin
	          bytes_start = 0
	          for j in 1:10
	              bytes_end = bytes_start + 16777216 - 1
	              @info "getting $bytes_start-$bytes_end"
	              newdata = S3.get_object("ryft-public-sample-data", "demo_searchlynx_example.tgz", Dict("headers" => Dict("Range"=>"bytes=$(bytes_start)-$(bytes_end)")); aws_config);
	              if length(newdata) != ((bytes_end - bytes_start) + 1)
					  @warn "Not same length" requested=((bytes_end - bytes_start) + 1) received=length(newdata)
			      end
	              bytes_start = bytes_end + 1
	          end
	      end
	  end
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 0-16777215
[ Info: getting 16777216-33554431
[ Info: getting 16777216-33554431
[ Info: getting 16777216-33554431
[ Info: getting 16777216-33554431
[ Info: getting 16777216-33554431
[ Info: getting 16777216-33554431
[ Info: getting 33554432-50331647
[ Info: getting 33554432-50331647
[ Info: getting 33554432-50331647
[ Info: getting 16777216-33554431
[ Info: getting 50331648-67108863
[ Info: getting 16777216-33554431
[ Info: getting 50331648-67108863
[ Info: getting 33554432-50331647
[ Info: getting 16777216-33554431
[ Info: getting 67108864-83886079
[ Info: getting 16777216-33554431
[ Info: getting 50331648-67108863
[ Info: getting 33554432-50331647
[ Info: getting 33554432-50331647
[ Info: getting 67108864-83886079
[ Info: getting 67108864-83886079
[ Info: getting 33554432-50331647
[ Info: getting 33554432-50331647
[ Info: getting 83886080-100663295
[ Info: getting 33554432-50331647
[ Info: getting 50331648-67108863
[ Info: getting 50331648-67108863
[ Info: getting 33554432-50331647
[ Info: getting 50331648-67108863
[ Info: getting 83886080-100663295
[ Info: getting 83886080-100663295
[ Info: getting 50331648-67108863
[ Info: getting 100663296-117440511
[ Info: getting 50331648-67108863
[ Info: getting 50331648-67108863
[ Info: getting 67108864-83886079
[ Info: getting 67108864-83886079
[ Info: getting 50331648-67108863
[ Info: getting 67108864-83886079
[ Info: getting 100663296-117440511
[ Info: getting 100663296-117440511
[ Info: getting 83886080-100663295
[ Info: getting 117440512-134217727
[ Info: getting 67108864-83886079
[ Info: getting 67108864-83886079
[ Info: getting 117440512-134217727
[ Info: getting 67108864-83886079
[ Info: getting 67108864-83886079
[ Info: getting 83886080-100663295
┌ Warning: Not same length
│   requested = 16777216
│   received = 15644967
└ @ Main REPL[8]:8
[ Info: getting 117440512-134217727
[ Info: getting 100663296-117440511
[ Info: getting 134217728-150994943
[ Info: getting 134217728-150994943
┌ Warning: Not same length
│   requested = 16777216
│   received = 16406089
└ @ Main REPL[8]:8
[ Info: getting 83886080-100663295
┌ Warning: Not same length
│   requested = 16777216
│   received = 16260881
└ @ Main REPL[8]:8
[ Info: getting 83886080-100663295
[ Info: getting 100663296-117440511
[ Info: getting 134217728-150994943
[ Info: getting 100663296-117440511
[ Info: getting 100663296-117440511
[ Info: getting 83886080-100663295
[ Info: getting 117440512-134217727
[ Info: getting 150994944-167772159
[ Info: getting 83886080-100663295
[ Info: getting 117440512-134217727
[ Info: getting 117440512-134217727
[ Info: getting 150994944-167772159
[ Info: getting 117440512-134217727
...
```

cc. @octogonapus

**Comment by Octogonapus** [comment]
Adding on to this that I did a bisect and determined this information:
- single threaded works on any version
- 1.70 bad
- 1.64 bad
- 1.63.1 bad ("occasional" failure rate)
- 1.63.0 bad (100% failure rate)
- 1.62 good

**Comment by IanButterworth** [comment]
Indeed the MWE is fine for me on 1.62.2

Also, I thought this might be the bug.. but it didn't fix master: https://github.com/IanButterworth/AWS.jl/commit/4942a82adf718d9d56da63e72e28d23989558876
It makes sense that that wasn't the bug because:
- From what I see the received data is always less than requested
- I added a `@debug` to show when `_http_request` retries were attempted, and this issue occurred in cases where there weren't any retries

But perhaps that is a real different bug?

**Comment by ericphanson** [comment]
Re- ETags, there’s an issue over in AWSS3: https://github.com/JuliaCloud/AWSS3.jl/issues/216

Re- 100% failure rate on AWS v1.63.0, that’s probably https://github.com/JuliaCloud/AWS.jl/issues/474

I wonder if that’s somehow related to your issue or just a red herring?

**Comment by IanButterworth** [comment]
As a sanity check, I believe this is a representative model of the buffer structure being used?
This doesn't error for me (but it is surprisingly slow.. perhaps this double-buffering approach slowing the process down?)
```
data = rand(UInt8, 16777216)
@sync for i in 1:100
    @async begin
        parent_buffer = IOBuffer()
        for j in 1:100
            @info "$i $j"
            buffer = Base.BufferStream()
            # sleep(rand() * 0.1) # optionally simulate a random download delay
            write(buffer, data)
            close(buffer)
            write(parent_buffer, buffer)
            newdata = take!(parent_buffer)
            length(newdata) != 16777216 && @warn "Not same length" requested=16777216 received=length(newdata)
        end
    end
end
```

**Comment by IanButterworth** [comment]
Just documenting one thing that hasn't worked. 
Talking to @staticfloat about this, it seems that `Base.BufferStream` has been seen to have `@async` issues, so I tried switching `Base.BufferStream()` out for `SimpleBufferStream.BufferStream()` https://github.com/staticfloat/SimpleBufferStream.jl
But the issue remains.
That seemed like a reasonable guess as moving from `Base.IOBuffer()` to `Base.BufferStream()` was one of the changes in the code path after 1.62.2 https://github.com/JuliaCloud/AWS.jl/compare/v1.62.2...v1.71.0

**Comment by IanButterworth** [comment]
Also, checking the header Content-length and Content-range has shown that they're equal to what's been requested. Only the data returned is less than expected. 

My guess is that this is a buffer handling/seeking issue. 

I.e. Perhaps the `_rewind` `seekstart` fails to go back to the start because of some async race?

**Comment by IanButterworth** [comment]
On master, when this happens, the `buffer` that's passed to HTTP.request has fewer bytes available after request returns, equal to that which are returned, so it seems not to be the buffer stacking that's the cause. HTTP.request is collecting fewer bytes

https://github.com/JuliaCloud/AWS.jl/blob/57696ba9a34dfff75f4c0dea3e42cba4c92e7001/src/utilities/request.jl#L160-L179

I continue to not be able to reproduce this on 1.62.2.
From what I can tell, the only difference about the input to HTTP.request on master vs 1.62.2 is that the `response_stream` arg is `nothing` on 1.62.2, but it is passed the `BufferStream` on master.

A successful response header
```
HTTP.Messages.Response:
"""
HTTP/1.1 206 Partial Content
x-amz-id-2: ...
x-amz-request-id: SWHNN2NF53MRYRJY
Date: Mon, 15 Nov 2021 02:36:40 GMT
Last-Modified: Wed, 14 Aug 2019 12:05:17 GMT
ETag: "751033c1e3e7703f653fefa9965c5ecc-1846"
Accept-Ranges: bytes
Content-Range: bytes 16777216-33554431/15478042270
Content-Type: application/x-tar
Server: AmazonS3
Content-Length: 16777216

[Message Body was streamed]"""
```
A short one
```
HTTP.Messages.Response:
"""
HTTP/1.1 206 Partial Content
x-amz-id-2: ...
x-amz-request-id: HF09BY30QTJ2Z7KG
Date: Mon, 15 Nov 2021 02:36:29 GMT
Last-Modified: Wed, 14 Aug 2019 12:05:17 GMT
ETag: "751033c1e3e7703f653fefa9965c5ecc-1846"
Accept-Ranges: bytes
Content-Range: bytes 33554432-50331647/15478042270
Content-Type: application/x-tar
Server: AmazonS3
Content-Length: 16777216
Connection: close

[Message Body was streamed]"""
```

Note `Connection: close`

**Comment by IanButterworth** [comment]
I think I've found the bug https://github.com/JuliaWeb/HTTP.jl/pull/778

The MWE and our real-world code is fixed using that.

Although, I don't know why 1.62.2 didn't hit this but later versions do

**Comment by IanButterworth** [comment]
Yeah, that sounds good

**Comment by IanButterworth** [comment]
Slight change of plan. See https://github.com/JuliaCloud/AWS.jl/pull/516 and https://github.com/JuliaWeb/HTTP.jl/pull/781

**Comment by omus** [comment]
I'll call out I was unable to reproduce the above problem using the code in the description. Tested on AWS.jl versions 1.70.0 and 1.63.1.

**Comment by IanButterworth** [comment]
Yeah, in our experience the MWE doesn't error for people with decent internet connections.

**Comment by IanButterworth** [comment]
I believe this can be closed as fixed by the linked PRs above
