### ISSUE TITLE
when region is missing

### ISSUE THREAD

**Issue by jondan99** [JuliaCloud/AWS.jl#529]
Hi All

I spent a lot of time, unsuccessfully, trying to make AWS.jl work. I could the command line aws just fine, but not AWS.jl. Finally I discovered why, I did not have region set in .aws/config  and that was never a problem on the command line.

So, I would suggest adding a check for region and inform the user, and perhaps allow one to add region to requests.

all the best, Jack

**Comment by mattBrzezinski** [comment]
We actually set the default region if one is not available to `us-east-1`. Could you provide some code example of what you were trying to do here?

**Comment by jondan99** [comment]
Hi 

thanks for the reply.

My region = eu-west-1 and I was accessing sns and s3

When I set region  in .aws/config the below works fine 

SNS.publish("test",Dict("Subject" => "Julia", "TargetArn"  =>  "my arn..."))
s3("GET", "/my-bucket...")

when region is not set both sns and s3 fail with these errors (and the "Invalid parameter: TargetArn" is particularly confusing) 

SNS.publish("test",Dict("Subject" => "Julia", "TargetArn"  =>  "my arn..."))
ERROR: AWS.AWSExceptions.AWSException: InvalidParameter -- Invalid parameter: TargetArn
HTTP.ExceptionRequest.StatusError(400, "POST", "/", HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
x-amzn-RequestId: 111b2190-0c8f-5bb6-8434-7bde9cf97c1e
Content-Type: text/xml
Content-Length: 275
Date: Tue, 04 Jan 2022 18:13:10 GMT

[Message Body was streamed]""")

<ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameter</Code>
    <Message>Invalid parameter: TargetArn</Message>
  </Error>
  Stacktrace:
  [1] macro expansion
  .....



s3("GET", "/my-bucket")ERROR: AWS.AWSExceptions.AWSException: 301 -- AWSException
HTTP.ExceptionRequest.StatusError(301, "GET", "/my-bucket", HTTP.Messages.Response:
"""
HTTP/1.1 301 Moved Permanently
x-amz-bucket-region: eu-west-1
x-amz-request-id: GZQEQ1K0MZBG3XSZ
x-amz-id-2: HklsCAnWAQRPzJs7lrLfHXpHEwUBDTuI93f8uqvD2o5/qWQiAqY4xlTqDx4fd1+9IAKbnH5WJC8=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Tue, 04 Jan 2022 18:15:43 GMT
Server: AmazonS3

""")
Stacktrace:
 [1] macro expansion
 ....

**Comment by mattBrzezinski** [comment]
Ah so I believe the failure here is because your resources are not in `us-east-1` (which is what is being set as the default).
I have seen this before with S3, I did not test this with anything else though. The error message is quite odd usually it would say something like, `Bucket is not in the region X`.

I'm not sure if there's more that we can do in the package here to address these things, as we need to pick a default region to set when making requests. If you do not have a region set, and your resources are not in this region, it will fail.

Maybe there could be some smart lookup to attempt to find the region for a resource, but that's probably overtly complex and not worth the time.

To resolve this problem going forward you would need to do one of:
- Set the region in your `~/.aws/config` file
- When creating an `AWSConfig` pass in a value for the kwarg `region`

**Comment by jondan99** [comment]
Hi

as you said, its easy to solve, once diagnosed,  set region in .aws/config, but that is not optimal as we have several regions in daily use, and switch between them in code. 

since AWS.jl loads the credentials on start, even a message that it found no region and set it to us-east-1  would help, and also the ability to set the region in the request also helps. (I could not find a way to do that in SNS, but one can on the command line) 

again, thanks for a great package. 

best, jack

**Comment by mattBrzezinski** [comment]
Without re-writing infrastructure to be in the same region. What you could do in your code is something like,

```julia
using AWS

@service SNS

EU_EAST_1_CONF = AWSConfig(; region="eu-east-1")
EU_WEST_1_CONF = AWSCfongi(; region="eu-west-1")

SNS.publish("test"; aws_config=EU_EAST_1_CONF)
S3.get_object("bucket"; aws_config=EU_WEST_1_CONF)
```

It's not ideal, but this would work around the problem. You will need to know the region before hand though for the resource. I believe that the `aws_config` kwarg is undocumented, I can make an update to the README if it's not in there already.

**Comment by jondan99** [comment]
this is perfect, thanks! 
we will make good use of it. 

be very good to have it in the README also

best, jack

**Comment by mattBrzezinski** [comment]
I'll double check the README, and open up a PR for it if it needs this information. I'll close this issue now, but if you have any other problems or questions in general feel free to cut an issue!

😄
