### ISSUE TITLE
JSON parser error when putting CloudWatch log events

### ISSUE THREAD

**Issue by Octogonapus** [JuliaCloud/AWS.jl#537]
I got this exception when submitting log data using CloudWatchLogs.jl, though it looks more like an AWS.jl issue given that some JSON parsing failed. Any idea how this exception can happen? Sorry, but I can't create an MWE for this one. If you don't have any ideas, feel free to just close this.

```
┌ Error: tid:1 Wiped logger event buffer due to exception.
│   exception =
│    Expected end of input
│    Line: 0
│    Around: ...1c4b0cd"}{"nextSequenceToken":...
│                        ^
│    
│    Stacktrace:
│      [1] error(s::String)
│        @ Base ./error.jl:33
│      [2] _error(message::String, ps::JSON.Parser.MemoryParserState)
│        @ JSON.Parser ~/.julia/packages/JSON/NeJ9k/src/Parser.jl:140
│      [3] parse(str::String; dicttype::Type, inttype::Type{Int64}, allownan::Bool, null::Nothing)
│        @ JSON.Parser ~/.julia/packages/JSON/NeJ9k/src/Parser.jl:453
│      [4] legacy_response(request::AWS.Request, response::AWS.Response{IOBuffer}; return_headers::Nothing)
│        @ AWS ~/.julia/packages/AWS/5goc1/src/deprecated.jl:160
│      [5] submit_request(aws::AWS.AWSConfig, request::AWS.Request; return_headers::Nothing)
│        @ AWS ~/.julia/packages/AWS/5goc1/src/utilities/request.jl:140
│      [6] (::AWS.JSONService)(operation::String, args::Dict{String, Any}; aws_config::AWS.AWSConfig, feature_set::AWS.FeatureSet)
│        @ AWS ~/.julia/packages/AWS/5goc1/src/AWS.jl:376
│      [7] put_log_events(logEvents::Vector{CloudWatchLogs.LogEvent}, logGroupName::String, logStreamName::String, params::Dict{String, String}; aws_config::AWS.AWSConfig)
│        @ CloudWatchLogs.CloudWatch_Logs ~/.julia/packages/AWS/5goc1/src/services/cloudwatch_logs.jl:1415
│      [8] _put_log_events(stream::CloudWatchLogs.CloudWatchLogStream, events::Vector{CloudWatchLogs.LogEvent})
│        @ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/gXZUD/src/stream.jl:199
```

**Comment by ericphanson** [comment]
try creating the service with
```julia
@service CloudWatchLogs use_response_type=true
```
which will return an object that isn't parsed immediately. It will try to parse it if you `show` it or call `parse` on it. That way you can at least get something back before the error in parsing.

**Comment by mattBrzezinski** [comment]
Looking into this now, I got a minimal example here,

```julia
using AWS
@service CloudWatch_Logs

events = [Dict("timestamp" => datetime2unix(now()) * 1000, "message" => "foobar"), Dict("timestamp" => datetime2unix(now()) * 1000, "message" => "foobar2")]

lgn = "/existing_log_group"
lsn = "existing_log_stream"

resp = CloudWatch_Logs.put_log_events(events, lgn, lsn)

for i in 1:5000
    nst = resp["nextSequenceToken"]
    resp = CloudWatch_Logs.put_log_events(events, lgn, lsn, Dict("sequenceToken" => nst))
end

ERROR: Expected end of input
Line: 0
Around: ...08ffee3"}{"nextSequenceToken":...
                    ^

Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] _error(message::String, ps::JSON.Parser.MemoryParserState)
   @ JSON.Parser ~/.julia/packages/JSON/NeJ9k/src/Parser.jl:140
 [3] parse(str::String; dicttype::Type, inttype::Type{Int64}, allownan::Bool, null::Nothing)
   @ JSON.Parser ~/.julia/packages/JSON/NeJ9k/src/Parser.jl:453
 [4] legacy_response(request::Request, response::AWS.Response{IOBuffer}; return_headers::Nothing)
   @ AWS ~/.julia/packages/AWS/5goc1/src/deprecated.jl:160
 [5] submit_request(aws::AWSConfig, request::Request; return_headers::Nothing)
   @ AWS ~/.julia/packages/AWS/5goc1/src/utilities/request.jl:140
 [6] (::JSONService)(operation::String, args::Dict{String, Any}; aws_config::AWSConfig, feature_set::AWS.FeatureSet)
   @ AWS ~/.julia/packages/AWS/5goc1/src/AWS.jl:376
 [7] put_log_events(logEvents::Vector{Dict{String, Any}}, logGroupName::String, logStreamName::String, params::Dict{String, String}; aws_config::AWSConfig)
   @ Main.CloudWatch_Logs ~/.julia/packages/AWS/5goc1/src/services/cloudwatch_logs.jl:1415
 [8] put_log_events(logEvents::Vector{Dict{String, Any}}, logGroupName::String, logStreamName::String, params::Dict{String, String})
   @ Main.CloudWatch_Logs ~/.julia/packages/AWS/5goc1/src/services/cloudwatch_logs.jl:1415
 [9] top-level scope
   @ ./REPL[32]:3
```

**Comment by mattBrzezinski** [comment]
Looks like when you get a throttling message this is what's return,

```julia
"{\"__type\":\"ThrottlingException\",\"message\":\"Rate exceeded for logStreamName manager/5825228e-b43c-4ef8-a5b4-9e1e308ffee3\"}{\"nextSequenceToken\":\"49622168642400204992093061932021562868795239426915565602\"}"
```

**Comment by mattBrzezinski** [comment]
Played around with this some more, here's the response back which occurs when we hit the throttling,

```julia
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
x-amzn-RequestId: b8d73068-465e-44fb-b3ae-29516267bcea
Content-Type: application/x-amz-json-1.1
Content-Length: 80
Date: Tue, 26 Apr 2022 18:40:44 GMT

[Message Body was streamed]"""
UInt8[0x7b, 0x22, 0x5f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x22, 0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x22, 0x52, 0x61, 0x74, 0x65, 0x20, 0x65, 0x78, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x20, 0x66, 0x6f, 0x72, 0x20, 0x6c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x20, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x35, 0x38, 0x32, 0x35, 0x32, 0x32, 0x38, 0x65, 0x2d, 0x62, 0x34, 0x33, 0x63, 0x2d, 0x34, 0x65, 0x66, 0x38, 0x2d, 0x61, 0x35, 0x62, 0x34, 0x2d, 0x39, 0x65, 0x31, 0x65, 0x33, 0x30, 0x38, 0x66, 0x66, 0x65, 0x65, 0x33, 0x22, 0x7d, 0x7b, 0x22, 0x6e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3a, 0x22, 0x34, 0x39, 0x36, 0x32, 0x32, 0x30, 0x32, 0x32, 0x31, 0x30, 0x37, 0x34, 0x38, 0x31, 0x37, 0x31, 0x34, 0x39, 0x39, 0x31, 0x35, 0x35, 0x31, 0x33, 0x37, 0x30, 0x34, 0x33, 0x37, 0x38, 0x39, 0x37, 0x37, 0x37, 0x39, 0x33, 0x34, 0x30, 0x31, 0x33, 0x37, 0x31, 0x36, 0x39, 0x39, 0x35, 0x37, 0x38, 0x38, 0x30, 0x33, 0x33, 0x34, 0x30, 0x33, 0x34, 0x22, 0x7d]
```

The header returns back a `200` code, but posts a ThrottlingException in the body of the response,

```
"{\"__type\":\"ThrottlingException\",\"message\":\"Rate exceeded for logStreamName manager/5825228e-b43c-4ef8-a5b4-9e1e308ffee3\"}{\"nextSequenceToken\":\"49622022107481714991551370437897779340137169957880334034\"}"
```

Going to cut an issue with AWS, while I work on a patch for this issue. The problem here is every other service returns back the HTTP code in the headers, and that's where we check if retries are needed.

**Comment by mattBrzezinski** [comment]
Hmmm... so looking into this some more we need to rework our retry system here I think.

We want to be checking to retry the request ideally [here](https://github.com/JuliaCloud/AWS.jl/blob/bf568c348060c6151faf5741550c84b06be42732/src/utilities/request.jl#L132) but w/ `Retry.jl` that's not possible because `@retry` isn't available unless it's in a `catch`? But we don't have any errors with the requests themselves, just the parsing the contents themselves...

**Comment by quinnj** [comment]
Ok, I've been digging into this as we're nearing a 1.0 release for HTTP.jl and I'm looking at 1) what kinds of breaking changes will affect big downstream dependents (like AWS.jl) and 2) outstanding "tricky" issues that may still need addressing in HTTP.jl to improve things: either in terms of additional functionality needed or improved robustness.

The core issue I've found here is that we're taking either the user-provided response_stream or an `IOBuffer` [here](https://github.com/JuliaCloud/AWS.jl/blob/d52c6391dd676e659d3b58f90ab81292fedc7db0/src/utilities/request.jl#L117), and then if there's one of a number of error conditions, including [throttling exception](https://github.com/JuliaCloud/AWS.jl/blob/d52c6391dd676e659d3b58f90ab81292fedc7db0/src/utilities/request.jl#L168) (as reported above), we end up retrying the request [here](https://github.com/JuliaCloud/AWS.jl/blob/d52c6391dd676e659d3b58f90ab81292fedc7db0/src/utilities/request.jl#L191). The problem there is that many of these "error conditions" from the 1st request resulted in an error response body being written to the response_stream, and then the request is retried with backoff and the subsequent retried request's response body is _also_ written to the response_stream, hence the weird JSON parsing issue we're seeing in several reports above where there are 2 JSON objects juxtapositioned right next to each other.

In terms of a solution, I'm still contemplating the best path forward. We have an open issue to [allow customizing retry behavior](https://github.com/JuliaWeb/HTTP.jl/issues/260), which could help by avoiding the need to do custom retry logic in AWS.jl. HTTP.jl already has _some_ logic for avoiding this kind of "double write" situation for retried requests, though currently not when a custom `response_stream` is provided, but that should be supported. I'll try to work on things a little locally and post an update here as things progress.

**Comment by ericphanson** [comment]
Btw AWS has two layers of retries; one in `submit_request` and one in `_http_request`. The inner layer handles this by using an extra buffer (at least I think that’s what it is for), while I don’t think the outer one has any handling for this situation hence the bug. We could probably work around the issue by also adding some handling in the outer retry to account for this case.
