### ISSUE TITLE
AWSEnv show shouldn't show secret key

### ISSUE THREAD

**Issue by sebastiang** [JuliaCloud/AWS.jl#54]
The default `show` displays secret key information. It's too easy to splash into the REPL or a log file, where it shouldn't really be displayed.

**Comment by samoconnor** [comment]
AWSCore.jl shows only the first 3 characters of secret key and access tokens : https://github.com/samoconnor/AWSCore.jl/blob/master/src/AWSCredentials.jl#L38

**Comment by jingpengwu** [comment]
I got a fix by adding a display function:

https://github.com/jingpengwu/AWS.jl/commit/97a1648b792964e13bdd67b65e44baba30e189db

**Comment by jingpengwu** [comment]
the PR was merged, I think we can close this issue.

**Comment by tanmaykm** [comment]
thanks
