### ISSUE TITLE
Interest in wrapping the AWS Common Runtime

### ISSUE THREAD

**Issue by Octogonapus** [JuliaCloud/AWS.jl#540]
Is there any interest in wrapping the [AWS Common Runtime](https://docs.aws.amazon.com/sdkref/latest/guide/common-runtime.html)? Or wrapping something like the [CRT for Python](https://github.com/awslabs/aws-crt-python) using PyCall.jl or PythonCall.jl? We have a need to use the AWS IoT SDK, so one of those projects would need to get wrapped at some level. Not sure if it fits in this package; maybe it would belong better as a new package in this organization?

**Comment by ericphanson** [comment]
If https://github.com/awslabs/aws-c-s3 can really get high throughput I think it would be really awesome to have. I think the first step with making C-libraries accessible to Julia is to build them with [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil), and the second is to wrap them, I’ve never done that but I think [Clang.jl](https://github.com/JuliaInterop/Clang.jl#binding-generator) is commonly used.

Probably AWS.jl isn’t the right repo for it, but JuliaCloud seems like a good place for such a repo.

**Comment by Octogonapus** [comment]
I have since created [AWSCRT_jll.jl](https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl), [LibAWSCRT.jl](https://github.com/Octogonapus/LibAWSCRT.jl) and [AWSCRT.jl](https://github.com/Octogonapus/AWSCRT.jl). In the future, I'll probably work on a higher level client for S3, but for now, my focus is on MQTT. This issue can probably be closed now.

**Comment by Octogonapus** [comment]
By the way, @ericphanson would you be interested in collaborating on the S3 client? We also have uses for very high S3 throughput, but they are in the future, so would you like me to contact you if we start working on one?

**Comment by ericphanson** [comment]
Yes, I would be interested! I’m not totally sure how much time I’ll have to help out but I’m definitely interested in improving high throughput s3 access from Julia.

**Comment by jrevels** [comment]
@Octogonapus I'll point out that @beacon-biosignals in general has a need for high-throughput reads and tabular data transforms in S3 - it's something we were planning on working on more in Q4 2022 / Q1 2023 :) would love to get a working group going at some point.

also, this is one of the primary topics we wanted to engage the community on in the JuliaCon 2022 BoF we're running on Data Engineering in Julia. Would love to discuss more there with you if you're be able to attend!
