### ISSUE TITLE
Should read credentials from ~/.aws if present

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaCloud/AWS.jl#56]
Should read credentials from ~/.aws, just like boto and the AWS CLI do.

**Comment by samoconnor** [comment]
AWSCore.jl does this. See https://github.com/samoconnor/AWSCore.jl/blob/master/src/AWSCredentials.jl#L59

**Comment by jingpengwu** [comment]
I have a function to do it, but depends on `EMIRT`. can copy corresponding functions to merge to AWS.jl.
https://github.com/seung-lab/EMIRT.jl/blob/master/plugins/aws.jl#L10

**Comment by jingpengwu** [comment]
added this capablility in a PR

https://github.com/JuliaCloud/AWS.jl/pull/73

the other changes does not pass the tests3.jl, not merged yet.

**Comment by tanmaykm** [comment]
Closing as #73 is merged now.
