### ISSUE TITLE
MethodError: no method matching bytes(::IOBuffer)  

### ISSUE THREAD

**Issue by haberdashPI** [JuliaCloud/AWS.jl#566]
This one is hard to nail down, but I'm writing down what I do know for sure, just in case anyone else has had this problem and/or has some sense from the scant information I do have below, what is going on.

The following works:

```
(temp) pkg> st
      Status `~/temp/Project.toml`
  [fbe9abb3] AWS v1.76.0
  [1c724243] AWSS3 v0.10.0
  [48062228] FilePathsBase v0.9.15

julia> using AWS, AWSS3, FilePathsBase
[ Info: Precompiling AWSS3 [1c724243-ef5b-51ab-93f4-b0a88ac62a95]

julia> global_aws_config(; region="us-east-2", profile="id-001")
```

But in another context, (with `using` of private packages with names that would reveal confidential information were I to write it down here), I get this error, with no stack trace, when making the same call to `global_aws_config`.

```
ERROR: MethodError: no method matching bytes(::IOBuffer)                                                                   
Closest candidates are:                                                                                                    
  bytes(::SubArray{UInt8}) at ~/.julia/packages/HTTP/aTjcj/src/IOExtras.jl:24                                              
  bytes(::Base.CodeUnits) at ~/.julia/packages/HTTP/aTjcj/src/IOExtras.jl:27                                               
  bytes(::String) at ~/.julia/packages/HTTP/aTjcj/src/IOExtras.jl:28     
```

???

I'm not really sure how helpful this info is at the moment, as I really need to track down *what* of my many dependencies triggers this weird error (and perhaps that is the package that actually has a bug). 

Notably, downgrading to AWS 1.75 also resolves the issue I'm having.

**Comment by ararslan** [comment]
The candidate methods are pointing to the HTTP version with slug `aTjcj`, which is v0.9.17. AWS v1.76.0 declares compatibility with HTTP v1.0+ only, so I have no idea how you could have ended up in this state... Reverting to v1.75 probably fixes it because that version _is_ compatible with HTTP v0.9.

**Comment by haberdashPI** [comment]
🤨 weird. Okay, I think this can safely be closed then.
