### ISSUE TITLE
Bad signature for Keys containing Unicode

### ISSUE THREAD

**Issue by mortenpi** [JuliaCloud/AWS.jl#592]
Using raw Unicode characters for `key`s leads to an invalid signature. This seems to be a reliable MWE:

```julia
using AWS: AWS
bucket = "mortenpi-test-bucket"
AWS.@service S3 use_response_type=true
aws_config = AWS.AWSConfig(region="ap-southeast-2")
params = Dict("body" => "123",)
S3.put_object(bucket, "📁", params; aws_config)
```

fails with

```
ERROR: AWS.AWSExceptions.AWSException: SignatureDoesNotMatch -- The request signature we calculated does not match the signature you provided. Check your key and signing method.

HTTP.Exceptions.StatusError(403, "PUT", "/mortenpi-test-bucket/📁", HTTP.Messages.Response:
"""
HTTP/1.1 403 Forbidden
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 21 Nov 2022 09:25:38 GMT
Server: AmazonS3

[Message Body was streamed]""")

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
...
```

Doing `URIs.escapepath()` on `key` does solve the issue. But I think this should also work as-is, because AWS does do limited escaping already?

https://github.com/JuliaCloud/AWS.jl/blob/4bd8b958f7172124922b32be449502faadddd489/src/utilities/utilities.jl#L46-L63

**Comment by quinnj** [comment]
Hmmm, this is weird; when I try this, I get the same failure, and in the error message response, it says the canonical request is:
```
PUT
/%C3%83%C2%B0%C3%82%C2%9F%C3%82%C2%93%C3%82%C2%81

accept:*/*
accept-encoding:gzip
content-length:9
host:relationalai-benchmarks-public.s3.us-east-1.amazonaws.com
user-agent:HTTP.jl/1.8.2
x-amz-date:20221130T060432Z
...
```
but I can't figure out how they're getting `/%C3%83%C2%B0%C3%82%C2%9F%C3%82%C2%93%C3%82%C2%81` as the canonical URI?? That seems to be just a garbage string in hex encoding.

**Comment by mortenpi** [comment]
@quinnj Could the issue be that HTTP.jl just happily writes [the raw UTF-8 bytes of the `.target` URL to the HTTP stream](https://github.com/JuliaWeb/HTTP.jl/blob/1d1e79c7192e525969099112960b456cc69a5a99/src/Messages.jl#L479-L481), but that's invalid HTTP, because everything should be ASCII/ISO-8859-1? And so the server (kind of correctly) misinterprets the URL?

**Comment by quinnj** [comment]
Yeah, possibly. I've wondered if we should be stricter about this in HTTP.jl; I just dont' want to get into a double escaping situation if people are already escaping.

**Comment by alancummings** [comment]
I'm getting this or similar error whenever a "#" is in the key (for me, it happens to always be in a /folder/)
Julia = 1.10.0

I have the same file uploaded to 2 different locations in a bucket; one of the locations has the "#" in the containing folder.

This succeeds:
S3.get_object(mybucket, "clean/path/test.csv")

These BOTH fail:
S3.get_object(mybucket, "path/with#/test.csv")   
    --> Signature does not match
S3.get_object(mybucket, URS.escapepath("path/with#/test.csv")
   --> NoSuchKey
