### ISSUE TITLE
Conflict of package versions when installing AWS.jl

### ISSUE THREAD

**Issue by psikonetik** [JuliaCloud/AWS.jl#605]
I am trying to install AWS.jl 1.81.0 however getting the following dependencies conflict on packages

1. HTTP needs to be above 1.0
2. AWSCore requires HTTP to be at max 0.9.17

How to solve this?

**Comment by mattBrzezinski** [comment]
This package is intended to completely replace [AWSCore.jl](https://github.com/JuliaCloud/AWSCore.jl). If for some reason you need functionality for it feel free to propose re-introducing it in this package. Alternatively you could attempt to bump AWSCore.jl to `HTTP@1+`, however I expect that to cause some headaches as it's quite out of date.

**Comment by psikonetik** [comment]
Thanks Matt, my julia folder was corrupted and thought AWSCore was a dependency of AWS. By deleting the folder I was able to completely uninstall AWSCore and then clean install AWS.
Solved!
