### ISSUE TITLE
Publicly hosted bors-ng instance is deprecated

### ISSUE THREAD

**Issue by omus** [JuliaCloud/AWS.jl#630]
When bors workflows run successfully you now see a warning about the publicly hosted bors-ng instance is deprecated and will be removed in the future (https://github.com/JuliaCloud/AWS.jl/pull/627#issuecomment-1577415040). Details on the deprecation: https://bors.tech/newsletter/2023/05/01/tmib-76/

The suggestioned options are to:
1. Host our own bors instance
2. Switch over to GitHub's built-in merge queue

Using a GitHub merge queue doesn't solve our particular problem as what we want to do is limit which users can trigger CI workflows.

**Comment by omus** [comment]
Looks like this may have just become urgent. I have PRs in AWS.jl and AWSS3.jl that don't seem to be responding to bors requests

**Comment by omus** [comment]
We can configure Git repos to require approval before running workflows: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories.

**Comment by omus** [comment]
I'm going to forge ahead with this work as it's blocking some other work of mine. We previously used "Require approval for first-time contributors" for this setting. I've now set it to "Require approval for all outside contributors" as we don't want a malicious actor submitting a trivial change and then being able to run whatever on CI:

![Screenshot 2023-06-07 at 13 05 32](https://github.com/JuliaCloud/AWS.jl/assets/1675958/f0d73d49-2240-437d-aaa8-b2d38bc2319a)

For our branch protection rules here's the old settings:


![Screenshot 2023-06-07 at 13 08 51](https://github.com/JuliaCloud/AWS.jl/assets/1675958/292b1cc1-e567-47db-93a2-5dbe20dcb1f0)

I've removed the `bors` requirement. Finally, I'll update our CI trigger rules from this:
```yaml
on:
  push:
    branches:
      - master
      - staging
      - trying
    tags: '*'
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 a.m. UTC
```
To automatically trigger on PRs and the `master` branch.

**Comment by omus** [comment]
GitHub is experiencing some issues with Pull Requests and Actions which may be the reason behind the bors issue I noticed. In any case bors is still deprecated and using a fully GitHub solutions seems better.

**Comment by iamed2** [comment]
I didn't expect that given their docs and how "first-time contributors" worked! That's excellent.

Who gets the ability to approve runs?

Are we comfortable with the amount of people with write access (i.e. run without approval) we currently have on AWS.jl? Should we move to require MFA for JuliaCloud?
