### ISSUE TITLE
Can´t read csv files from S3

### ISSUE THREAD

**Issue by jplicona** [JuliaCloud/AWS.jl#646]
Hi, I want to read csv and parquet files from S3 AWS in my local machine using VSCode. However, I am not quite sure how to do it. I have been trying to find something on the documentation, but it hasnt been helpful.

```
using AWS.AWSServices: s3
s3("GET", "s3://test1/test_file.csv")

#GET THE FOLLOWING ERROR:
ERROR: Can't find AWS credentials!
```
How can i specify the credentials (aws_access_key_id, aws_secret_access_key)? What is the right way to write the julia script?
In python I was able to connect to S3 by using boto3 and awswrangler:

```
import awswrangler as wr
import boto3

# Configure AWS credentials
session = boto3.Session(
    aws_access_key_id="123456789",
    aws_secret_access_key="asdfghjklqwertyuiozxcvbnm"
)

import awswrangler as wr

df = wr.s3.read_csv(
    path="s3://test1/test_file.csv",
    boto3_session=session
)

print(df)
```
Help. Thanks in advance

**Comment by ararslan** [comment]
In case this is still relevant for you nearly one year to the day from when you posted it...

There are a few ways you could go about this. The workflow I typically use is with [AWSS3.jl](https://github.com/JuliaCloud/AWSS3.jl) and its `S3Path` type, which can be passed directly to `CSV.read`. The only use of AWS.jl in this case is for credential management.
```julia
using AWS, AWSS3, CSV, DataFrames

# If you don't have a profile defined in `~/.aws/config`:
config = AWSConfig(AWSCredentials("123456789", "asdfghjklqwertyuiozxcvbnm"))
# Or if you do have a profile, you can use it by name:
config = AWSConfig(; profile="whatever")

df = CSV.read(S3Path("s3://test1/test_file.csv"; config), DataFrame)
```
