### ISSUE TITLE
LoadError: Can't find AWS credentials!

### ISSUE THREAD

**Issue by vpanichkin** [JuliaCloud/AWS.jl#648]
Hey, folks.

## I got a problem once I try to run this code

```
using AWSS3, AWS, FilePathsBase;


region = "eu-west-1"
aws_config = global_aws_config(; region = region)
```

## The error with the stack trace:

```
ERROR: LoadError: Can't find AWS credentials!

Stacktrace:
 [1] AWSCredentials(; profile::Nothing, throw_cred_error::Bool)
   @ AWS ~/.julia/packages/AWS/wwLKx/src/AWSCredentials.jl:145
 [2] #global_aws_config#91
   @ ~/.julia/packages/AWS/wwLKx/src/AWS.jl:81 [inlined]

```

Affected versions:

- 1.90
- 1.84

Could you suggest some fix that could help to resolve the issue?

**Comment by mattBrzezinski** [comment]
Are your `~/.aws/config` or `~/.aws/credentials` files populate?

**Comment by vpanichkin** [comment]
Good morning, yes I have an aws config. Weird think, that nothing was changed in them, but suddenly stopped working

```
> cat ~/.aws/config
[default]
region = eu-west-1
```

**Comment by vpanichkin** [comment]
Good news. The issue disappeared automatically. Apparently, some glitch in the AWS
