### ISSUE TITLE
precompiling uses env vars from compile-time, not run-time

### ISSUE THREAD

**Issue by s2maki** [JuliaCloud/AWS.jl#67]
In `src/AWS.jl`, lines 35-59 refer to environment variables in order to set up credentials.  Since those lines are in open code, the variables will be initialized based on ENV at precompile time rather than when the package gets used.

Recommend this code get moved into __init__, and the rest of the package get scanned visually for other similar problems.

**Comment by mdpradeep** [comment]
Fixed with https://github.com/JuliaCloud/AWS.jl/pull/69
