### ISSUE TITLE
Can't install package - Julia 0.4.6

### ISSUE THREAD

**Issue by alexfakos** [JuliaCloud/AWS.jl#74]
I am running Julia 0.4.6 on ubuntu 14.04.5 LTS
I installed all the required packages and I am getting the following errors. Do you know what the problem can be? Thanks a lot. 

WARNING: Error during initialization of module GMP:
ErrorException("The dynamically loaded GMP library (version 6.1.0 with __gmp_bits_per_limb == 64)
does not correspond to the compile time version (version 5.1.3 with __gmp_bits_per_limb == 64).
Please rebuild Julia.")

=============================[ ERROR: HttpParser ]==============================

LoadError: could not spawn `unzip -x /home/ubuntu/.julia/v0.4/HttpParser/deps/downloads/v2.7.1.zip -d /home/ubuntu/.julia/v0.4/HttpParser/deps/src`: n
o such file or directory (ENOENT)
while loading /home/ubuntu/.julia/v0.4/HttpParser/deps/build.jl, in expression starting on line 71
# 

INFO: Building MbedTLS
cmake command not found. installing cmake is required for building from source.
===============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`./cmake_check.sh`, ProcessExited(1)) [1]
while loading /home/ubuntu/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 74
# 

INFO: Building LightXML
INFO: Building AWS

===================================================================[ BUILD ERRORS ]===================================================================

WARNING: HttpParser and MbedTLS had build errors.
- packages with build errors remain installed in /home/ubuntu/.julia/v0.4
- build the package(s) and all dependencies with `Pkg.build("HttpParser", "MbedTLS")`
- build a single package by running its `deps/build.jl` script
#

**Comment by abhijithch** [comment]
Looks like you do not have `unzip` available on your machine. Please install using `apt-get install unzip` and then do a `Pkg.build("AWS")`, it should install without any errors.
