### ISSUE TITLE
Tagging new version/updating METADATA?

### ISSUE THREAD

**Issue by JohnHBrock** [JuliaCloud/AWS.jl#78]
It looks like a new version hasn't been tagged in quite a while, can someone with permissions do that? master has some fixes I would like.

**Comment by JohnHBrock** [comment]
Bump.

**Comment by josefsachsconning** [comment]
Could someone please comment on the status?

**Comment by tanmaykm** [comment]
v0.3.0 was tagged: https://github.com/JuliaLang/METADATA.jl/pull/10246
