### ISSUE TITLE
Adding back region-aware S3 request

### ISSUE THREAD

**Issue by pevnak** [JuliaCloud/AWS.jl#80]
Hello All,
I am starting to experiment with this package, as I am interested in SQS and S3. Living in Europe, it is vital for me to access eu-west-1 region. Nevertheless it does not work by default, because in function do_http() in S3.jl on line 684 someone has commented
`	
## if( isempty(env.region) )
    	url = "https://s3.amazonaws.com" * full_path
	## else
    	## url = "https://s3-$(env.region).amazonaws.com" * full_path
	## end

`
Can someone uncomment >

I do not know the state of this package, because even transfer to 0.5 seems to be unfinished, as there are lots of warnings, even though in pull requests I see that someone has fixed the warning.

**Comment by merl-dev** [comment]
@mdpradeep This pull request works fine, please merge changes.
