### ISSUE TITLE
how to get the number of remaining messages in SQS?

### ISSUE THREAD

**Issue by jingpengwu** [JuliaCloud/AWS.jl#83]
Could anyone help? Is there any function to get the number of remaining messages in SQS? Or tell whether the queue is empty or not?
Thanks.

**Comment by merl-dev** [comment]
You need to do that accounting in your own code. Working with AWS SQS can be tricky, and you should refer to the AWS SQS docs, or site like Stackoverflow for more information on how to get the precise number of messages left in a queue.

**Comment by jingpengwu** [comment]
thanks, it would be nice to have this function in AWS.jl though.

**Comment by samoconnor** [comment]
Hi @jingpengwu,
The `GetQueueAttributes` API might help you.
There is a Julia implementation here:
https://github.com/samoconnor/AWSSQS.jl/blob/master/src/AWSSQS.jl#L214

**Comment by jingpengwu** [comment]
@samoconnor Thanks for the notice, your package looks pretty handy. I may have a try later.
