### ISSUE TITLE
AWS S3 and JLD

### ISSUE THREAD

**Issue by pevnak** [JuliaCloud/AWS.jl#86]
Hello All,
I am working on large machine learning project, where data are stored in S3. My plan is to asynchronously download data to workers that would learn the Neural Network or do other magic on them.

So far, I have encountered two limitations. 
Firstly,
```
AWS.S3.get_bkt(env,bucket_name,options=AWS.S3.GetBucketOptions(max_keys=2000))
```
returns at most 1000 elements of the bucket, even though I requested more.

Secondly, when I download the file stored as jld, I cannot parse it. After downloading the file issuing
```
r = AWS.S3.get_object(env,bkt,file_name);
r.obj is of type Array{UInt8,1} but I cannot load it using load(IOBuffer(r.obj)).
```

Has anyone tried to overcome these issues?

Thanks for suggestions.
Tomas

**Comment by aviks** [comment]
The first may be a limitation of S3. Are you sure the underlying api allows retrieving more elements at once? 

For the second, have you tried checksumming the file contents to see if they have somehow been corrupted in transit?

**Comment by pevnak** [comment]
Dear Avik,
I have tried to list the content with the amazon's aws cli and it lists all the content. The difference is that aws cli allows you to list similarly to directory, which means that you can go recursively, which might be the difference. The solution might be to add functionality to traverse S3 like a dictionary structure.

Regarding loading JLD, I have tried to save the object to a file and read it as a file, and this works well.

Thanks for answers.
Best wishes,
Tomas

**Comment by samoconnor** [comment]
The API has `IsTruncated` and `marker` to handle long object lists.

See example Julia code here: https://github.com/samoconnor/AWSS3.jl/blob/master/src/AWSS3.jl#L277
